USE [master]
GO

/****** Object:  Database [UserTaskManagement]    Script Date: 4/25/2020 11:37:21 PM ******/
CREATE DATABASE [UserTaskManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserTaskManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UserTaskManagement.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UserTaskManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UserTaskManagement_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UserTaskManagement] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserTaskManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserTaskManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserTaskManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserTaskManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserTaskManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserTaskManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserTaskManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserTaskManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserTaskManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserTaskManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserTaskManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserTaskManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserTaskManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserTaskManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserTaskManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserTaskManagement] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UserTaskManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserTaskManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserTaskManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserTaskManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserTaskManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserTaskManagement] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [UserTaskManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserTaskManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [UserTaskManagement] SET  MULTI_USER 
GO

ALTER DATABASE [UserTaskManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserTaskManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserTaskManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserTaskManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UserTaskManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserTaskManagement] SET  READ_WRITE 
GO


